import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar'
import {ThemeProvider} from '@/components/theme-provider'
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        
        >

      <body className={poppins.className}>
        <Navbar />
        {children}
        </body>
      </ThemeProvider>
    </html>
  )
}
